-- Account-level scaffolding for Longaeva POC sandbox.
-- Idempotent: re-runs are safe.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS POC_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
       AUTO_SUSPEND = 60
       AUTO_RESUME = TRUE
       INITIALLY_SUSPENDED = TRUE
       COMMENT = 'Longaeva POC sandbox warehouse (BH-526)';

CREATE ROLE IF NOT EXISTS LONGAEVA_POC_ROLE
  COMMENT = 'Owns LONGAEVA_POC and LONGAEVA_VENDOR_SHARE_SIM databases';

GRANT USAGE ON WAREHOUSE POC_WH TO ROLE LONGAEVA_POC_ROLE;
GRANT ROLE LONGAEVA_POC_ROLE TO USER KURICHINCA;

CREATE DATABASE IF NOT EXISTS LONGAEVA_POC
  COMMENT = 'Simulates Longaeva warehouse (bronze/silver/gold/ref/semantic)';

CREATE DATABASE IF NOT EXISTS LONGAEVA_VENDOR_SHARE_SIM
  COMMENT = 'Simulates an inbound Snowflake Data Share from a vendor';

GRANT OWNERSHIP ON DATABASE LONGAEVA_POC
  TO ROLE LONGAEVA_POC_ROLE COPY CURRENT GRANTS;

GRANT OWNERSHIP ON DATABASE LONGAEVA_VENDOR_SHARE_SIM
  TO ROLE LONGAEVA_POC_ROLE COPY CURRENT GRANTS;
